### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy

### ISSUE THREAD

**Issue by Floko122** [RisQFLan/RisQFLan#1]
I get a NoClassDefFoundError for two classes in javax.annotation the corresponding jar is in the plugins folder and replacing it with the most recent version did not fix the problem either.

See the attached log-file (.metadata/.log) for more detail
[log.txt](https://github.com/RisQFLan/RisQFLan/files/6375228/log.txt)

**Comment by andrea-vandin** [comment]
Hello.
The source code here is not aligned with the current one.

If you are interested in using the tool, please visit the wiki. We have just uploaded a new version.
